pool:
  vmImage: vs2017-win2016

variables:
  solution: './ClientLibrary/Samples/ClientSamples.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: Docker@2
  inputs:
    containerRegistry: 'cc'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: Ansible@0
  inputs:
    ansibleInterface: 'remoteMachine'
    connectionOverSsh: 'test'
    playbookSourceRemoteMachine: 'ansibleMachine'
    inventoriesRemoteMachine: 'noInventory'